engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config:
      config: .eslintrc-codeclimate
  fixme:
    enabled: false
ratings:
  paths:
  - src/**
